{% set name = "oct-to-tiff" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oct_to_tiff-{{ version }}.tar.gz
  sha256: 3adadd68f256e1b2c79af0f7db127e5eb17746a5c6f0ea5c9d5c14473ef7fa7f

build:
  entry_points:
    - oct-to-tiff = oct_to_tiff.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - defusedxml
    - numpy
    - tifffile

test:
  imports:
    - oct_to_tiff
  commands:
    - pip check
    - oct-to-tiff --help
  requires:
    - pip

about:
  home: https://github.com/camlloyd/oct-to-tiff
  summary: A command line tool for converting optical coherence tomography angiography (OCTA) data.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - camlloyd
