{% set name = "oct-to-tiff" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oct_to_tiff-{{ version }}.tar.gz
  sha256: 3e842aff08cd11f11bcee252a37a6530fde884a632551612c4f7478a8d8210cb

build:
  entry_points:
    - oct-to-tiff = oct_to_tiff.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - tifffile

test:
  imports:
    - oct_to_tiff
  commands:
    - pip check
    - oct-to-tiff --help
  requires:
    - pip

about:
  home: https://github.com/camlloyd/oct-to-tiff
  summary: A command line tool for converting optical coherence tomography angiography (OCTA) data.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - camlloyd
